services:
  frontend:
    build:
      context: ./frontend
      dockerfile: frontend.Dockerfile
      args:
        - REACT_APP_API_URL=http://localhost:5000/api
        - REACT_APP_AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
        - REACT_APP_AZURE_TENANT_ID=${AZURE_TENANT_ID}
        - REACT_APP_AZURE_REDIRECT_URI=${AZURE_REDIRECT_URI}
        - REACT_APP_BYPASS_AUTH=${BYPASS_AUTH:-true}
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - ezra-network

  backend:
    build:
      context: ./backend
      dockerfile: backend.Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/ezra.db
      - AzureAd__Instance=https://login.microsoftonline.com/
      - AzureAd__Domain=${AZURE_DOMAIN}
      - AzureAd__TenantId=${AZURE_TENANT_ID}
      - AzureAd__ClientId=${AZURE_CLIENT_ID}
      - AzureAd__Scopes=api://${AZURE_CLIENT_ID}/access_as_user
      - ASPNETCORE_URLS=http://+:5000
      - Development__BypassAuthentication=${BYPASS_AUTH:-true}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:3000}
    volumes:
      - ./data:/app/data
    networks:
      - ezra-network

networks:
  ezra-network:
    driver: bridge

volumes:
  data:
