name: PR Validation

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate:
    name: Validate PR
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for proper diff
    
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v40
      with:
        files_yaml: |
          backend:
            - 'backend/**'
          frontend:
            - 'frontend/**'
          docker:
            - '**/Dockerfile'
            - '**/docker-compose*.yml'
    
    - name: Setup .NET
      if: steps.changed-files.outputs.backend_any_changed == 'true'
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Build Backend
      if: steps.changed-files.outputs.backend_any_changed == 'true'
      run: |
        echo "Backend files changed, building..."
        dotnet restore
        dotnet build --configuration Release --no-restore
      working-directory: ./backend
    
    - name: Run Backend Tests
      if: steps.changed-files.outputs.backend_any_changed == 'true'
      run: dotnet test --no-restore --verbosity normal
      working-directory: ./backend
    
    - name: Setup Node.js
      if: steps.changed-files.outputs.frontend_any_changed == 'true'
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install Frontend Dependencies
      if: steps.changed-files.outputs.frontend_any_changed == 'true'
      run: npm ci
      working-directory: ./frontend
    
    - name: Build Frontend
      if: steps.changed-files.outputs.frontend_any_changed == 'true'
      run: npm run build
      working-directory: ./frontend
      env:
        CI: true
        REACT_APP_API_URL: ${{ vars.REACT_APP_API_URL || '/api' }}
        REACT_APP_AZURE_CLIENT_ID: ${{ secrets.REACT_APP_AZURE_CLIENT_ID || 'dummy-client-id' }}
        REACT_APP_AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID || 'dummy-tenant-id' }}
        REACT_APP_AZURE_REDIRECT_URI: ${{ vars.REACT_APP_AZURE_REDIRECT_URI || 'http://localhost:3000' }}
        REACT_APP_BYPASS_AUTH: ${{ 'false' }}
    
    - name: Run Frontend Tests
      if: steps.changed-files.outputs.frontend_any_changed == 'true'
      run: npm test -- --coverage --watchAll=false
      working-directory: ./frontend
      env:
        CI: true
    
    - name: Validate Docker Compose
      if: steps.changed-files.outputs.docker_any_changed == 'true'
      run: |
        echo "Docker files changed, validating..."
        docker compose config

  size-check:
    name: Bundle Size Check
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install dependencies
      run: npm ci
      working-directory: ./frontend
    
    - name: Build and analyze bundle
      run: |
        npm run build
        echo "Build completed. Bundle sizes:"
        ls -lah build/static/js/*.js | awk '{print $9, $5}'
      working-directory: ./frontend
      env:
        CI: true
        REACT_APP_API_URL: ${{ vars.REACT_APP_API_URL || '/api' }}
        REACT_APP_AZURE_CLIENT_ID: ${{ vars.REACT_APP_AZURE_CLIENT_ID || 'dummy-client-id' }}
        REACT_APP_AZURE_TENANT_ID: ${{ vars.REACT_APP_AZURE_TENANT_ID || 'dummy-tenant-id' }}
        REACT_APP_AZURE_REDIRECT_URI: ${{ vars.REACT_APP_AZURE_REDIRECT_URI || 'http://localhost:3000' }}
        REACT_APP_BYPASS_AUTH: ${{ vars.REACT_APP_BYPASS_AUTH || 'true' }}
